[project]
name = "quantum-maturity-app"
version = "0.1.0"
description = "Quantum Maturity Score Application"
requires-python = ">=3.11"
dependencies = [
    "streamlit>=1.45.1",
    "psycopg2-binary>=2.9.10",
    "sqlalchemy>=2.0.41",
    "pandas",
    "plotly",
    "transformers",
    "torch",
]
